CXX = g++
CXXFLAGS = -std=c++23 -Wall -Wextra -Wpedantic -pedantic-errors -Wconversion -Wshadow
TARGET = build/main
SRC = main.cpp

all:
	mkdir -p build
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET)

run: all
	./$(TARGET)

clean:
	rm -rf build
